/* E */

#include <stdio.h>

int main(){
    printf("EEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEE\nEEE\nEEE\nEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEE\nEEE\nEEE\nEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEE\n");

    return 0;
}